### ISSUE TITLE
automl is showing best model = 0.63 & when testing with validation data im seeing 0.5

### ISSUE THREAD

**Issue by RachelKellam** [Azure-Samples/AzureMLWorkshop#25] opened 2020-03-06 18:32 UTC
![image](https://user-images.githubusercontent.com/53354089/76111773-c0584e80-5f95-11ea-977a-bdcad7379c16.png)
Challenge 0.1B

I have a copy on the notebook if needed

**Comment by RachelKellam** [comment] 2020-03-06 18:33
![image](https://user-images.githubusercontent.com/53354089/76111832-e54cc180-5f95-11ea-82a8-fae6dc0506fe.png)

**Comment by RachelKellam** [comment] 2020-03-06 18:44
someone else - "its annoying to do all this work and come out with a random coin flip"

**Comment by JenTownsend** [comment] 2020-03-06 19:00
I will note that the Accuracy is actually 96%.  But the AUC doesn't seem to match with this. In particular it is disheartening because the Challenge01A, predicting off the same data, gave the same accuracy rate (with a 0.5 threshold on to classify as 1), and has a a higher AUC.

![image](https://user-images.githubusercontent.com/61885619/76113769-91dc7280-5f99-11ea-9906-02bcf18f4fce.png)

**Comment by CESARDELATORRE** [comment] 2020-03-07 01:37
Closing this bug since I'm following up on this: 
https://github.com/Azure-Samples/AzureMLWorkshop/issues/30

Plus I also created a bug in VSO we're researching with Anup:
https://msdata.visualstudio.com/Vienna/_queries/edit/639785/?fullScreen=true&triage=true

**Closed by CESARDELATORRE** 2020-03-07 01:37 UTC

**Comment by CESARDELATORRE** [comment] 2020-03-09 18:59
Fixed. AUC needs to be calculated with the probabilities, not the predictions.
Interestingly (Looks like a bug/issue in LightGBM, see: https://github.com/microsoft/LightGBM/issues/198#issuecomment-489419106), the original plain LightGBM was returning probabilities when using 'gbdt' when predicting instead of 0 and 1, even when the 'objective' is 'binary', not regression...:
ImageImage
![image](https://user-images.githubusercontent.com/1712635/76247832-6e196680-61fd-11ea-9683-fe41065fafb1.png)

Also, related to the issue/bug above from LightGBM, when using 'gbdt' you cannot call the method to get the predictions, as I get this error. That's a bug, since the objective is 'binary' classification:

Image
That's why when calculating AUC it was "right", because it was obtaining probabilities, not predictions (0/1):
Image
The original LightGBM notebook uses 'Booster' because it was the one who won 'Porto Seguro Kaggle competition':
https://github.com/microsoft/LightGBM/issues/198#issuecomment-489419782


But the predictions when using the AutoML model return 0 or 1, which is more logical, since this is a binary classification:
Image

Therefore we need to obtain the probabilities in an explicit way:

Image

Then AUC is calculated right when providing the probabilities column:
Image

It looks that it doesn't matter if it is weighted or not, in this case.
